/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    A: typeof import('./src/components/a/src/a.vue')['default']
    Chart: typeof import('./src/components/chart/src/chart.vue')['default']
    ColorPicker: typeof import('./src/components/colorPicker/src/colorPicker.vue')['default']
    ColorPickerAppTheme: typeof import('./src/components/colorPicker/src/colorPickerAppTheme.vue')['default']
    DeleteButton: typeof import('./src/components/deleteButton/src/deleteButton.vue')['default']
    Demo: typeof import('./src/components/demo/src/demo.vue')['default']
    Editor: typeof import('./src/components/editor/src/editor.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElButtonGroup: typeof import('element-plus/es')['ElButtonGroup']
    ElColorPicker: typeof import('element-plus/es')['ElColorPicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElPopconfirm: typeof import('element-plus/es')['ElPopconfirm']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSpace: typeof import('element-plus/es')['ElSpace']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    Form: typeof import('./src/components/form/src/form.vue')['default']
    FormDialog: typeof import('./src/components/formDialog/src/formDialog.vue')['default']
    Icon: typeof import('./src/components/icon/src/icon.vue')['default']
    Img: typeof import('./src/components/img/src/img.vue')['default']
    ImgAvatar: typeof import('./src/components/img/src/imgAvatar.vue')['default']
    ImgDefault: typeof import('./src/components/img/src/imgDefault.vue')['default']
    Loading: typeof import('./src/components/loading/src/loading.vue')['default']
    LoadingLottie: typeof import('./src/components/loading/src/loading-lottie.vue')['default']
    Lottie: typeof import('./src/components/lottie/src/lottie.vue')['default']
    Markdown: typeof import('./src/components/markdown/src/markdown.vue')['default']
    MarkdownView: typeof import('./src/components/markdown/src/markdownView.vue')['default']
    MCheckboxGroup: typeof import('./src/components/form/src/components/MCheckboxGroup.vue')['default']
    MColorPicker: typeof import('@/components')['MColorPicker']
    MForm: typeof import('@/components')['MForm']
    MIcon: typeof import('@/components')['MIcon']
    MImg: typeof import('@/components')['MImg']
    MLottie: typeof import('@/components')['MLottie']
    MRadioGroup: typeof import('./src/components/form/src/components/MRadioGroup.vue')['default']
    MSelect: typeof import('./src/components/form/src/components/MSelect.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Table: typeof import('./src/components/table/src/table.vue')['default']
    Upload: typeof import('./src/components/upload/src/upload.vue')['default']
    ViewFile: typeof import('./src/components/upload/src/viewFile.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
